name: Agent Treasury Policy Linter
description: Fails CI when agent-treasury policy guardrails are missing (allowlists, caps, timelock/quorum, pause/logging).
author: Amara-ops
branding:
  icon: shield
  color: blue
inputs:
  policy:
    description: Path to policy JSON
    required: true
  report:
    description: Path to write JSON report
    required: false
    default: policy.report.json
  strict:
    description: Treat warnings as errors
    required: false
    default: 'false'
  version:
    description: Linter ref (tag or branch) in main repo (Amara-ops/agent-guardrails-policy-linter)
    required: false
    default: main
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Fetch linter dist from main repo
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p .linter
        base_url="https://raw.githubusercontent.com/Amara-ops/agent-guardrails-policy-linter/${{ inputs.version }}"
        # Download compiled JS
        for f in cli.js rules.js schema.js; do
          echo "::group::Download dist/$f"
          curl -sSfL -o ".linter/$f" "$base_url/dist/$f"
          echo "::endgroup::"
        done
        # Download JSON schema expected by schema.js (required at ../schema.json)
        echo "::group::Download schema.json"
        curl -sSfL -o "schema.json" "$base_url/schema.json"
        echo "::endgroup::"
    - name: Install runtime deps (Ajv) and set ESM type
      shell: bash
      run: |
        set -euo pipefail
        npm --prefix .linter init -y >/dev/null 2>&1
        # Silence ESM warning and align with our ESM build
        node -e 'let p=require("./.linter/package.json"); p.type="module"; require("fs").writeFileSync("./.linter/package.json", JSON.stringify(p,null,2));'
        npm --prefix .linter i ajv@8
    - name: Run linter
      shell: bash
      run: |
        set -euo pipefail
        STRICT_FLAG=""
        if [ "${{ inputs.strict }}" = "true" ]; then STRICT_FLAG="--strict"; fi
        node .linter/cli.js "${{ inputs.policy }}" --report "${{ inputs.report }}" $STRICT_FLAG
